### ISSUE TITLE
No install information

### ISSUE THREAD

**Issue by EzraEn1** [EzraEn1/bteguide#12]
For this to be the authoritative centralised source of information re: BTE, we have to get the basics down. Installation is one of those basics. Manual installs are something we need to write a simple guide for, as they can be repetitive and potentially complex. Perhaps we should suggest MultiMC for this.

**Comment by metalcupcake5** [comment]
#17, added basic info, still need many details, such as adding MultiMC, more into detail about how to install forge, etc

**Comment by EzraEn1** [comment]
Thanks to @metalcupcake5, we now have an install tutorial!
