### ISSUE TITLE
Beginning translation difficult

### ISSUE THREAD

**Issue by EzraEn1** [EzraEn1/bteguide#7]
```bash
 git checkout -b lang-xx
 git pull origin\lang-xx
 ./make.bat gettext
 sphinx-intl update -p build/gettext -l xx
```

A translator should not have to do all this just to start translating.

**Comment by metalcupcake5** [comment]
Perhaps a `bat` or `sh` file could be used to just automate everything

**Comment by EzraEn1** [comment]
Good idea, I will have to start work on a buildtool.
